apiVersion: v1
kind: Pod
metadata:
  name: day34-app
spec:
  containers:
    - name: app
      image: nginx:1.27
      envFrom:
        - configMapRef:
            name: day34-config
        - secretRef:
            name: day34-secret
