apiVersion: apps/v1
kind: Deployment

metadata:
  name: day33-nginx

spec:
  replicas: 2

  selector:
    matchLabels:
      app: day33-nginx

  template:
    metadata:
      labels:
        app: day33-nginx

    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
