apiVersion: v1
kind: Pod
metadata:
  name: day35-pod
spec:
  containers:
    - name: app
      image: nginx:1.27
      volumeMounts:
        - name: storage
          mountPath: /data
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: day35-pvc
